#SCREEN PINS

LCD_MOSI = 10
LCD_SCK = 11
LCD_CS = 8
LCD_DC = 24
LCD_RST = 25
LCD_WIDTH = 240
LCD_HEIGHT = 320
LCD_SPI_BUS = 0
LCD_SPI_DEVICE = 0

#ROTARY ENCODER

ENC_CLK = 17
ENC_DT = 27
ENC_SW = 22


#BUTTONS
BTN1 = 23
BTN2 = 5

#ALERTING

LED_DATA = 18
LED_COUNT = 8 #CHANGE IT TO YOUR ACTUAL LED COUNT 
BUZZER_PINS = 12

# Update these if you move the device

OBSERVER_LAT = 25.3463
OBSERVER_LON = 55.4209
OBSERVER_ELEV= 0

# OpenSky planes API
PLANES_API_URL = "https://opensky-network.org/api/states/all" 
PLANES_API_TIMEOUT = 1.5
PLANES_BBOX_DEGREES = 1.0 
PLANES_MAX_RANGE_KM = 400.0

# Local dump1090 /ADS-B
PLANES_LOCAL_URL = "http://pi/dump1090/data/aircraft.json" #PLACEHOLDER!!!!

PLANES_LOCAL_TIMEOUT = 0.3  