M48
; DRILL file KiCad 10.0.0 date 2026-04-14T22:47:29
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-14T22:47:29+04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.750
%
G90
G05
T1
X55.6Y-90.61
X55.6Y-96.39
T2
X89.23Y-92.03
X89.23Y-150.03
X112.23Y-92.03
X112.23Y-150.03
M30
